### ISSUE TITLE
index is always false

### ISSUE THREAD

**Issue by michelkluger** [sbi-rviot/ph_table#12]
I would like to have the option to have the output with index as well

**Comment by sbi-rviot** [comment]
Hello @michelkluger!
Thank you for using my library :) - Yes, it is doable.
I'll try come back to you next week.
Renaud

**Comment by sbi-rviot** [comment]
@michelkluger  - It have been added to the latest version. Could you please confirm and please start this library if you have not yet to help the community! Thanks

**Comment by michelkluger** [comment]
the new implementation works, but there is still something a bit off in the coloring of the index

see image 
![image](https://user-images.githubusercontent.com/50880307/121661552-9947d100-caa4-11eb-82ad-78ea453f30e3.png)

**Comment by sbi-rviot** [comment]
A bit off is the first one correct? "Inconsistent Beneficiary Country"?

**Comment by michelkluger** [comment]
the "Inconsistent Beneficiary Country" followed the correct formatting, the rest of the index has not

**Comment by sbi-rviot** [comment]
Corrected in version **0.9.10**
Please confirm.

**Comment by michelkluger** [comment]
in my case the issue was not resolved, plus  a print was left inside the function

![image](https://user-images.githubusercontent.com/50880307/121675239-71ac3500-cab3-11eb-870f-8eb27bf21eca.png)

**Comment by sbi-rviot** [comment]
Could you tell me why it is not resvoled? it seems to me that your index have now the good style no?

for the print - it was corrected in version 10, as described above no?

**Comment by michelkluger** [comment]
the first line has no bold, the rest is bold,

and in my view, the formatting should be consistent with the header row

**Comment by sbi-rviot** [comment]
I'll update the bold. you are correct :)
I'll think I'll have deserved for you to start this library ^^
I'll do it today.

**Comment by michelkluger** [comment]
awesome, thank you!

**Comment by sbi-rviot** [comment]
Hello @michelkluger - it is done with the version 11.
Could you confirm?
And do not forget to star this repository - Thanks :)

**Comment by michelkluger** [comment]
I can confirm that it is fixed, thanks
